### ISSUE TITLE
Collation of redcap_project_ownership table doesn't match REDCap conventions

### ISSUE THREAD

**Issue by pbchase** [ctsit/collect_project_ownership_at_creation#6]
The existing collation of the [redcap_project_ownership table](https://github.com/pbchase/collect_project_ownership_at_creation/blob/9960b56aff575c0b8fbc38fd572d325be08aa723/ExternalModule.php#L49) is very inconvenient for joining it with other REDCap tables. I ran into this problem trying to join on username. The collation should be utf8_unicode_ci to match REDCap conventions.  e.g., the new table should be created as 

```
CREATE TABLE  redcap_project_ownership (
    pid INT NOT NULL,
    username VARCHAR(128),
    email VARCHAR(128),
    firstname VARCHAR(128),
    lastname VARCHAR(128),
    PRIMARY KEY (pid)
) collate utf8_unicode_ci;
```

Any alter table statement on the existing table would need to convert the data in the table as well.  e.g.,

```
alter table redcap_project_ownership
CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
```

**Comment by pbchase** [comment]
Note, the collation change has been added to the create table statement via commit a01bfefd

**Comment by tbembersimeao** [comment]
Closing.
